# 使用官方 Laravel 映像
FROM composer:2 as builder
FROM php:8.1.0-apache

# 複製 composer 安裝的檔案
COPY --from=builder /usr/bin/composer /usr/bin/composer

# 安裝相依套件
RUN apt-get update && \
    apt-get install -y \
        git \
        zip \
        unzip 

RUN docker-php-ext-install sockets

# 複製 Laravel 專案到映像
COPY . /var/www/html

# 安裝 Laravel 相依套件
RUN composer install --optimize-autoloader

# 設定權限
ARG DOCKER_UID
ENV DOCKER_UID=${DOCKER_UID}
RUN useradd -u ${DOCKER_UID} -m the-whale
RUN usermod -G www-data,the-whale,root,adm the-whale
RUN chmod -R 777 /var/www/html/storage

# 啟用 Apache 的 rewrite module
RUN a2enmod rewrite

# 將 Apache 的工作目錄設為 Laravel 入口點
RUN sed -i -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf
